### ISSUE TITLE
不好意思搞不太清楚用途

### ISSUE THREAD

**Issue by derekhsu** [Kuingsmile/PicList-Core#1]
我想請教您，我佈署好了PicList在我的Kubernetes裡面，這個服務目前是只有後端是嗎？
要配合前端的應用才能使用是嗎？

**Comment by Kuingsmile** [comment]
core项目只有后端，可以配合typora或者obsidian之类的软件使用。 另外https://github.com/Kuingsmile/PicList 这个项目是跨平台的桌面端GUI软件，基于core内核配套了GUI界面。
