### ISSUE TITLE
关于typora使用PicList-Core

### ISSUE THREAD

**Issue by xiaozhang959** [Kuingsmile/PicList-Core#2]
请问作者我原来有安装了picGo-core，现在需要怎么把typora的picGo-core换成您的PicList-core？ 目前我已经安装了picList-core了，但是在typora中每次使用的配置文件似乎还是之前picGo-core的。

**Comment by Kuingsmile** [comment]
> 请问作者我原来有安装了picGo-core，现在需要怎么把typora的picGo-core换成您的PicList-core？ 目前我已经安装了picList-core了，但是在typora中每次使用的配置文件似乎还是之前picGo-core的。

用自定义命令，如果是`npm install -g piclist`全局安装的piclist话，填`picgo upload`就可以，不然的话用which picgo找到路径，然后填完整路径加upload

![image](https://github.com/Kuingsmile/PicList-Core/assets/96409857/5b41c28d-945b-4bb4-82b4-8059b0f331ca)
