### ISSUE TITLE
docker部署后通过命令行配置和安装插件的方法

### ISSUE THREAD

**Issue by Urabartin** [Kuingsmile/PicList-Core#3]
通过docker compose部署了core，但是在`docker exec -it piclist sh`进入容器调试时，运行`/usr/local/bin/picgo`会报错：`': No such file or directory`。不使用docker，使用npm安装则正常使用，此时容器挂载的卷改为配置目录，容器内的picgo也能按预期使用

搜索一番后无果，不清楚这是镜像的原因还是我用不明白docker，想请教一下，谢谢！

**Comment by Kuingsmile** [comment]
进去容器后用`node /usr/local/bin/picgo`来执行命令，`node /usr/local/bin/picgo -h`可以查看说明

**Comment by Urabartin** [comment]
谢谢，我犯蠢了。光看文档里命令行部分，没注意容器配置里的`command`写明白了
