### ISSUE TITLE
upload时如何按照时间戳重命名？

### ISSUE THREAD

**Issue by yslin1995** [Kuingsmile/PicList-Core#4]
大佬你好，我在远程服务端部署了piclist-core，怎么能做到按照接收图片的时间戳重命名后，再上传到对应图床呢？Piclist的客户端好像自带有这个功能，但是服务端没看到重命名的文档～

**Comment by Kuingsmile** [comment]
`picgo set buildin`，选择`rename`进行设置，具体的支持的占位符如下：
![image](https://github.com/Kuingsmile/PicList-Core/assets/96409857/feb754f9-c905-4c70-be6a-afaa59a7b050)

或者直接修改配置文件也可以，对应的配置项如下
```json
"buildIn": {
    "rename": {
      "enable": false,
      "format": "img/{filename}"
    }
}
```

**Comment by yslin1995** [comment]
@Kuingsmile 请问目前支持设置两个config.json吗（有两个不同的aliyun OSS存不同内容），希望能在URL传参的时候用configName作区分～
