### ISSUE TITLE
小白请教一下：如何使用删除图片接口

### ISSUE THREAD

**Issue by laye0619** [Kuingsmile/PicList-Core#5]
查了半天的文档没有查到，在这里请教一下：
1. 我使用docker搭建的piclist，上传图片成功，想问一下如果使用删除接口需要在配置文件中加入什么配置字段吗？
2. 例如我
          上传的在cloudflare r2的地址是：https://r2.myname.com/04/aaabbb.png
          我piclist server的地址是http://192.168.1.50/delete
          我应该发送什么post请求给这个接口（json），才能实现删除https://r2.myname.com/04/aaabbb.png  这个图片？

十分感谢！

**Comment by Kuingsmile** [comment]
core版本不支持删除功能哦  请使用桌面版本  因为删除功能是需要记录上传时的信息的 需要有数据库
