### ISSUE TITLE
local uploader 配置方面疑问

### ISSUE THREAD

**Issue by yqs112358** [Kuingsmile/PicList-Core#7]
我这边使用docker部署，进容器把uploader换成了local，整体配置文件如下：
```
{
  "picBed": {
    "uploader": "local",
    "current": "local",
    "smms": {
      "token": ""
    },
    "local": {
      "path": "/usr/local/images/",
      "customUrl": "https://image.xxxx.com:12345",
      "webPath": "images/"
    }
  },
  "picgoPlugins": {}
}
```
通过 https://image.xxxx.com:12345/upload 上传图片`test.png`无问题，但是从返回的URL访问图片 https://image.xxxx.com:12345/images/test.png 时则被拒绝，报错：
`[PicList Server] don't support [/images/test.png] endpoint`
请问这个如何解决，是我对webPath的理解不正确嘛？

可以确定不是docker/文件权限方面的问题。piclist独有的这些功能我看没做文档，有点搞不太明白
<br/><br/>

PS：简单看了下源码，好像piclist-server只负责接收上传嘛？也就是说需要再单独给local的上传目录弄一个nginx/caddy服务器？（其实我感觉稍微加两行处理一下local特殊情况的GET请求也可以，，）

**Comment by Kuingsmile** [comment]
> 我这边使用docker部署，进容器把uploader换成了local，整体配置文件如下：
> 
> ```
> {
>   "picBed": {
>     "uploader": "local",
>     "current": "local",
>     "smms": {
>       "token": ""
>     },
>     "local": {
>       "path": "/usr/local/images/",
>       "customUrl": "https://image.xxxx.com:12345",
>       "webPath": "images/"
>     }
>   },
>   "picgoPlugins": {}
> }
> ```
> 
> 通过 https://image.xxxx.com:12345/upload 上传图片`test.png`无问题，但是从返回的URL访问图片 https://image.xxxx.com:12345/images/test.png 时则被拒绝，报错： `[PicList Server] don't support [/images/test.png] endpoint` 请问这个如何解决，是我对webPath的理解不正确嘛？
> 
> 可以确定不是docker/文件权限方面的问题。piclist独有的这些功能我看没做文档，有点搞不太明白
> 
> PS：简单看了下源码，好像piclist-server只负责接收上传嘛？也就是说需要再单独给local的上传目录弄一个nginx/caddy服务器？（其实我感觉稍微加两行处理一下local特殊情况的GET请求也可以，，

piclist的端口只是上传接口，不是web server
web server比较简单 python应该可以一键启动一个文件服务器
