### ISSUE TITLE
buildin rename中可用的占位符参数有哪些？

### ISSUE THREAD

**Issue by yqs112358** [Kuingsmile/PicList-Core#8]
如题，即设置项中的`设定重命名格式 format: ({filename})`，这里例子只给了一个{filename}，其他可选的占位符参数有哪些？这个feature好像也没有相关文档来着

**Comment by Kuingsmile** [comment]
https://piclist.cn/configure.html#%E4%B8%8A%E4%BC%A0%E8%AE%BE%E7%BD%AE

![image](https://github.com/user-attachments/assets/30150152-11a1-4850-a592-e392fe7613be)
