### ISSUE TITLE
piclist-core在server模式下有办法支持配置文件/图床切换么？

### ISSUE THREAD

**Issue by yqs112358** [Kuingsmile/PicList-Core#9]
> Tip: PicList支持通过设置picbed和configName两个URL查询参数来指定上传图床和配置文件。例如：http://127.0.0.1:36677/upload?picbed=aws-s3&configName=piclist-test 该配置将会使用aws-s3图床，并且使用piclist-test配置文件。

piclist-core使用server模式部署的时候，可以在上传时指定配置文件/图床后端么？

默认配置文件应该是`/root/.piclist/config.json`，我将其复制为test.json并做修改，重启服务器后尝试通过`https://xxxx/upload?configName=test`上传，发现仍然使用的是原来旧的配置文件

**Comment by Kuingsmile** [comment]
可以 但需要使用piclist桌面版的配置文件，将桌面版的配置文件复制到config.json里
